# Generated by Django 3.1.4 on 2021-02-02 09:51

from django.db import migrations, models
import fifteenmmdp.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllMeterFiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=255)),
                ('month', models.CharField(max_length=255)),
                ('zippedMeterFile', models.FileField(upload_to='media', validators=[fifteenmmdp.validators.validate_file_extension])),
            ],
        ),
    ]
