# Generated by Django 3.1.4 on 2021-02-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifteenmmdp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allmeterfiles',
            name='dirStructure',
            field=models.TextField(null=True),
        ),
    ]
