# Generated by Django 3.1.4 on 2021-02-07 07:55

from django.db import migrations, models
import fifteenmmdp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('fifteenmmdp', '0002_allmeterfiles_dirstructure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allmeterfiles',
            name='zippedMeterFile',
            field=models.FileField(upload_to='fifteenmmdp/media', validators=[fifteenmmdp.validators.validate_file_extension]),
        ),
    ]
