# Generated by Django 3.1.4 on 2021-02-07 08:04

from django.db import migrations, models
import fifteenmmdp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('fifteenmmdp', '0003_auto_20210207_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allmeterfiles',
            name='zippedMeterFile',
            field=models.FileField(upload_to='meterFile', validators=[fifteenmmdp.validators.validate_file_extension]),
        ),
    ]
