# Generated by Django 3.1.4 on 2021-02-07 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fifteenmmdp.models
import fifteenmmdp.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fifteenmmdp', '0004_auto_20210207_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='allmeterfiles',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='allmeterfiles',
            name='zippedMeterFile',
            field=models.FileField(upload_to=fifteenmmdp.models.upload_path, validators=[fifteenmmdp.validators.validate_file_extension]),
        ),
    ]
