# Generated by Django 3.1.4 on 2021-02-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifteenmmdp', '0007_auto_20210210_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='allmeterfiles',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
