# Generated by Django 3.1.4 on 2021-02-17 04:34

from django.db import migrations, models
import fifteenmmdp.models
import fifteenmmdp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('fifteenmmdp', '0008_allmeterfiles_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='allmeterfiles',
            name='mergedFile',
            field=models.FileField(max_length=1023, null=True, upload_to=fifteenmmdp.models.upload_path_mergedFile, validators=[fifteenmmdp.validators.validate_file_extension_npc]),
        ),
    ]
