# Generated by Django 3.1.4 on 2021-02-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifteenmmdp', '0010_auto_20210217_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='allmeterfiles',
            name='endDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='allmeterfiles',
            name='startDate',
            field=models.DateField(null=True),
        ),
    ]
