# Generated by Django 3.1.4 on 2021-02-21 12:25

from django.db import migrations, models
import django.db.models.deletion
import fifteenmmdp.models
import fifteenmmdp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('fifteenmmdp', '0013_validatedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealMeterMWHFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fileName', models.CharField(max_length=255)),
                ('filePath', models.CharField(max_length=1023)),
                ('realMeterMWHFile', models.FileField(max_length=1023, storage=fifteenmmdp.models.OverwriteStorage(), upload_to=fifteenmmdp.models.upload_path_realMeterMWH, validators=[fifteenmmdp.validators.validate_file_extension_MWH])),
                ('meterFile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fifteenmmdp.allmeterfiles')),
            ],
        ),
    ]
