# Generated by Django 3.1.4 on 2021-02-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifteenmmdp', '0014_realmetermwhfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='allmeterfiles',
            name='dirStructureFictMWH',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='allmeterfiles',
            name='dirStructureFinalOutput',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='allmeterfiles',
            name='dirStructureRealMWH',
            field=models.TextField(null=True),
        ),
    ]
