# Generated by Django 3.1.4 on 2021-02-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifteenmmdp', '0018_auto_20210224_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realmetermwhfile',
            name='fileName',
        ),
        migrations.RemoveField(
            model_name='realmetermwhfile',
            name='filePath',
        ),
        migrations.RemoveField(
            model_name='realmetermwhfile',
            name='realMeterMWHFile',
        ),
        migrations.AddField(
            model_name='realmetermwhfile',
            name='dirStructureRealMWH',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='realmetermwhfile',
            name='mwhDictionary',
            field=models.TextField(null=True),
        ),
    ]
