# Generated by Django 3.1.4 on 2021-02-24 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fifteenmmdp', '0019_auto_20210224_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allmeterfiles',
            name='dirStructureFictMWH',
        ),
        migrations.RemoveField(
            model_name='allmeterfiles',
            name='dirStructureFinalOutput',
        ),
        migrations.RemoveField(
            model_name='allmeterfiles',
            name='dirStructureRealMWH',
        ),
    ]
