# Generated by Django 3.1.4 on 2021-02-24 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fifteenmmdp', '0020_auto_20210224_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allmeterfiles',
            name='dirStructure',
        ),
        migrations.RemoveField(
            model_name='npcfile',
            name='fileName',
        ),
        migrations.RemoveField(
            model_name='npcfile',
            name='filePath',
        ),
        migrations.RemoveField(
            model_name='npcfile',
            name='npcFile',
        ),
        migrations.AddField(
            model_name='npcfile',
            name='dirStructureNPC',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='npcfile',
            name='npcDictionary',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='npcfile',
            name='meterFile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fifteenmmdp.allmeterfiles'),
        ),
    ]
