# Generated by Django 3.1.4 on 2021-03-01 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fifteenmmdp', '0021_auto_20210224_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='FictMeterMWHFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dirStructureFictMWH', models.TextField(null=True)),
                ('fictMwhDictionary', models.TextField(null=True)),
                ('meterFile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fifteenmmdp.allmeterfiles')),
            ],
        ),
    ]
