# Generated by Django 3.1.4 on 2021-03-02 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fifteenmmdp', '0022_fictmetermwhfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalOutputFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dirStructureFinalOutput', models.TextField(null=True)),
                ('finalOutputDictionary', models.TextField(null=True)),
                ('meterFile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fifteenmmdp.allmeterfiles')),
            ],
        ),
    ]
