# Generated by Django 3.1.4 on 2021-03-07 14:56

from django.db import migrations, models
import fifteenmmdp.models


class Migration(migrations.Migration):

    dependencies = [
        ('fifteenmmdp', '0024_necessaryfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='necessaryfile',
            name='necessaryFile',
            field=models.FileField(max_length=1023, storage=fifteenmmdp.models.OverwriteStorage(), upload_to=fifteenmmdp.models.upload_path_necessaryFile),
        ),
    ]
